# Generated by Django 4.2.1 on 2023-05-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='projects_tags',
            field=models.ManyToManyField(to='projects.project'),
        ),
    ]
